context('Pizza Order Form Test', () => {
  it('Anasayfa order-pizza button test', () => {
    cy.visit('http://localhost:3000/')
    cy.get('[data-cy="order-pizza"]').click()
    cy.location('pathname').should('eq', `/pizza`)
    cy.go('back')
  })
  beforeEach(() => {
    cy.visit('http://localhost:3000/pizza')
  })
  it('Sayfa acilisinda button disabled kontrolu', () => {
    cy.get('[data-cy= "order-button"]').should('have.disabled', true)
  })

  it('Test name-input', () => {
    cy.get('[data-cy = "name-input"]')
      .type('a')
      .should('have.value', 'a')
      .should('have.class', 'is-invalid')
    cy.get('[data-cy= "order-button"]').should('have.disabled', true)
    cy.get('[data-cy= "name-input"]')
      .clear()
      .type('ab')
      .should('have.value', 'ab')
      .clear()
      .should('have.class', 'is-invalid')
    cy.get('[data-cy= "order-button"]').should('have.disabled', true)
    cy.get('[data-cy= "name-input"]')
      .type('Sertac')
      .should('have.value', 'Sertac')
      .should('not.have.class', 'is-invalid')
  })

  it('Test size-dropdown', () => {
    cy.get('[data-cy="size-dropdown"]').should('have.value', null)
    cy.get('[data-cy="size-dropdown"]')
      .select('Küçük')
      .should('have.value', 'Küçük')
    cy.get('[data-cy="size-dropdown"]')
      .select('Orta')
      .should('have.value', 'Orta')
    cy.get('[data-cy="size-dropdown"]')
      .select('Büyük')
      .should('have.value', 'Büyük')
    cy.get('[data-cy="size-dropdown"]')
      .select('XL')
      .should('have.value', 'XL')
  })

  it('.check() - radio elements', () => {
    cy.get('[type="radio"]')
      .not('[disabled]')
      .check()
      .should('be.checked')
  })
  it('.check() - checkbox elements', () => {
    cy.get('[type="checkbox"]')
      .not('[disabled]')
      .check()
      .should('be.checked')
      .should('have.class', 'is-invalid')
    cy.get('[data-cy= "order-button"]').should('have.disabled', true)
    cy.get('[type="checkbox"]')
      .not('[disabled]')
      .uncheck()
      .should('not.be.checked')
  })
  it('Test special-text', () => {
    cy.get('[data-cy = "special-text"]')
      .type('Servis istemiyorum')
      .should('have.value', 'Servis istemiyorum')
  })
})
